### ISSUE TITLE
docker-compose w/ crond doesn’t stay running

### ISSUE THREAD

**Issue by Chovin** [openbridge/ob_bulkstash#12]
running `docker-compose up` with the RCLONE_CRONFILE env var set doesn’t run, a perpetual command was needed to keep it running like `command: tail -f /dev/null`

**Comment by guillaumelachaud** [comment]
I am having the same issue. How did you get it up running ? For me, it runs once and the exits properly so cron can never fire.

**Comment by guillaumelachaud** [comment]
I ended up doing the `command: tail -f /dev/null` trick but I think this should be explicitly written in the documentation. `RCLONE_SYNC_COMMAND` also lacks documentation.

**Comment by tspicer** [comment]
This is working, I just started this up following the docs:

```
Load average: 0.02 0.10 0.14 3/786 24
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   16     1 root     S     4788   0%   3   0% monit -c /etc/monitrc
   18     0 root     S     2312   0%   0   0% bash
    1     0 root     S     2304   0%   0   0% bash
   24    18 root     R     1528   0%   2   0% top
   10     1 root     S     1516   0%   2   0% crond -b
```
Notice both monitors and cron are running in the background.

It is hard to diagnose any problems with no background provided. If you want support on this, you need to provide your full ENV and your full docker-compose file (or your full run command). It is not really possible to diagnose any setup problems without this.

`rclone.sh` is sample utility script. It shows how you can accomplish running CRON and a bash script. If you look at the script the  `RCLONE_SYNC_COMMAND` does what is sounds like it does; it runs your rclone commands.

Like most things open source, feel free to contribute to the project, make enhancements, refine docs and I would be more than happy to review and update!

**Comment by guillaumelachaud** [comment]
Do they keep running after rclone completes (and without a restart policy set to `always`) ? This is the main question here. 

Thanks for the invitation to contribute, I'll try to put up a PR when I have some time.

**Comment by tspicer** [comment]
Yes, monit controls the process (`https://github.com/openbridge/ob_bulkstash/blob/develop/monit.d/check_crond`). If for some reason crond stops running, monit will make sure it is started. 

So if like you say crond is exiting, I'm assuming that monit is not doing its job or your config is not what I would expect. For example, I can run a KILL command on crond and monit DOES restart the process. Even if crond did exit after running, it should be running.  

Like I said, without details on your setup I cannot really comment further.

```
monit status
Monit 5.25.2 uptime: 35m

Process 'crond'
  status                       OK
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  pid                          10
  parent pid                   1
  uid                          0
  effective uid                0
  gid                          0
  uptime                       35m
  threads                      1
  children                     0
  cpu                          0.0%
  cpu total                    0.0%
  memory                       0.0% [44 kB]
  memory total                 0.0% [44 kB]
  security attribute           -
  disk write                   0 B/s [16 kB total]
  data collected               Sun, 24 Mar 2019 22:22:55

System '6e058f011cd3'
  status                       OK
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  load average                 [0.16] [0.08] [0.07]
  cpu                          0.2%us 0.7%sy 0.0%wa
  memory usage                 1.1 GB [54.1%]
  swap usage                   44.6 MB [4.4%]
  uptime                       1d 2h 56m
  boot time                    Sat, 23 Mar 2019 19:27:04
  data collected               Sun, 24 Mar 2019 22:22:55
```

**Comment by tspicer** [comment]
ps, I just testing crond running through a loop with `* * * * * ` and rclone would execute the ls command without incident. crond never exited after rclone finished. Also tried this with a simple bash echo, same thing.

**Comment by guillaumelachaud** [comment]
Ok. I will double check. Right now I am having an issue with the rclone.sh when it converts the ENV variables to a file in /cron/rclone.env, the sed regexp adds double quotes which don't play well with the double quotes of my RCLONE_CONFIG_GDRIVE_TOKEN (everything works fine with a SA file though). 

Because I don't want to confuse everything, I'll report back when I have figured this part to see if this failure in launching rclone is what stops monit. In my case, docker-entrypoint.sh is not blocking on any command. So when it reaches the end, docker terminates the container as it is expected to do. In my case, neither crond nor monit are blocking the shell script from reaching the end. I completely agree with you that it's impossible for you to figure out what's wrong without knowing what my config is so I'll post my full config if I don't make any progress :-)

Thanks!

**Comment by tspicer** [comment]
Yes, the regex might need some work. It is not a strength of mine, but I could see where it might cause some funky behavior in certain cases.

**Comment by guillaumelachaud** [comment]
I confirm the regexp was causing some issues for me and that escaping the characters in the token solved tit. But this is a different problem so I'll create a separate issue (and PR :-P) for that.

Now that this is cleared, I confirm that the `run` function in the docker-entrypoint.sh is not blocking as neither `crond` nor `monit` are. They both instantly exit successfully and as there's no loop whatsoever or any perpetual command to prevent reaching the end docker-entrypoint.sh, docker terminates the container (which is the original matter of this thread :-)). Rather than giving you my full config, I'll come up with a minimum reproductible usecase to share with you.

**Comment by tspicer** [comment]
Awesome! Sounds like a plan

**Comment by guillaumelachaud** [comment]
Alright, I have over simplified the minimum use case but it should be representative of the problem.

Here is `docker-compose.yml`

```version: '2'
services:
  rclone:
    image: openbridge/ob_bulkstash
    environment:
     RCLONE_CRONFILE: /cron/crontab.conf
     RCLONE_SYNC_COMMAND: rclone version
    volumes:
     - /srv/rclone/crontab.conf:/cron/crontab.conf
    command: rclone version
```

And here is `crontab.conf`:

```
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
*/10 * * * * /usr/bin/env bash -c /rclone.sh run 2>&1
```

To me, the expected behavior is the following:
 - run `rclone version` as soon as the container start
 - run `rclone version` every 10 minutes through cron

But when  running `docker-compose up`, here is the output:

```
reating network "tmp_default" with the default driver
Creating tmp_rclone_1 ... done
Attaching to tmp_rclone_1
rclone_1  | SHELL=/bin/bash
rclone_1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
rclone_1  | */10 * * * * /usr/bin/env bash -c /rclone.sh run 2>&1
rclone_1  | set daemon 10
rclone_1  | set pidfile /var/run/monit.pid
rclone_1  | set statefile /var/run/monit.state
rclone_1  | set httpd port 2849 and
rclone_1  |     use address localhost
rclone_1  |     allow localhost
rclone_1  | set logfile syslog
rclone_1  | set eventqueue
rclone_1  |     basedir /var/run
rclone_1  |     slots 100
rclone_1  | include /etc/monit.d/*
rclone_1  |  New Monit id: b92aca65e514c0ab1c39222b2d1018cf
rclone_1  |  Stored in '/root/.monit.id'
rclone_1  | Starting Monit 5.25.2 daemon with http interface at [localhost]:2849
rclone_1  | rclone v1.46
rclone_1  | - os/arch: linux/amd64
rclone_1  | - go version: go1.11.5
tmp_rclone_1 exited with code 0
```

As soon as `rclone version` as run, the container exits. It is just the version print but it could be any other rclone command that takes longer, this is just to simplify the testing and debugging. crond and monit  are indeed running the background but only until docker-entrypoint.sh finishes executing. At that point docker assumes the container is done and stops it (as expected) which, in turn, also stops monit from managing crond inside the container.

**Comment by tspicer** [comment]
I will need to think about this a little more, but I'm not sure that is unexpected behavior. Setting the command to `rclone version` should run once. You are telling the container to run it, it does and then it exits. The container stops because it completed the process you told it to run. This is why the example compose uses `bash` as the command, then uses another process (ie cron, monit...) to run commands.

This is not much different than running 
```
/ssh docker run openbridge/ob_bulkstash:1.46 rclone version
rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5
➜  /ssh 
```
Using bash, it will persist (ie run as a background), then you run the same thing, and the process exits but not the container.
```
docker exec -it 6e058f011cd3 bash
bash-4.4# rclone version
rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5
bash-4.4# 
```

**Comment by Chovin** [comment]
with @GuillaumeLachaud 's minimal compose file, I've stuck `bash` in as you've suggested
```yml
version: '3'
services:
  rclone:
    image: openbridge/ob_bulkstash
    environment:
     RCLONE_CRONFILE: /cron/crontab.conf
     RCLONE_SYNC_COMMAND: rclone version
    volumes:
     - ${CRONTAB_CONF_FILE}:/cron/crontab.conf
    command: bash
```

starting it with `bash` as the command does not keep it running. It starts bash and then exits. Monit does not keep it open because `bash` is not the process running Monit.

```bash
$ docker-compose up
Recreating rclone_test_rclone_1 ... done
Attaching to rclone_test_rclone_1
rclone_1  | SHELL=/bin/bash
rclone_1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
rclone_1  | 0 0 * * * curl -fsS --retry 3 ${RCLONE_HEALTHCHECK_URL}/start && /usr/bin/env bash -c "/rclone.sh run" && curl -fsS --retry 3 ${RCLONE_HEALTHCHECK_URL}set daemon 10
rclone_1  | set pidfile /var/run/monit.pid
rclone_1  | set statefile /var/run/monit.state
rclone_1  | set httpd port 2849 and
rclone_1  |     use address localhost
rclone_1  |     allow localhost
rclone_1  | set logfile syslog
rclone_1  | set eventqueue
rclone_1  |     basedir /var/run
rclone_1  |     slots 100
rclone_1  | include /etc/monit.d/*
rclone_1  |  New Monit id: c4140dc23d1ecd4ef6e73930879fb919
rclone_1  |  Stored in '/root/.monit.id'
rclone_1  | Starting Monit 5.25.1 daemon with http interface at [localhost]:2849
rclone_test_rclone_1 exited with code 0

$ docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                NAMES
```

You are right in that specifying a `command` for images you pull is usually meant for single execution, but leaving the `command` out like you'd normally do for other services causes it to exit

```yml
version: '3'
services:
  rclone:
    image: openbridge/ob_bulkstash
    environment:
     RCLONE_CRONFILE: /cron/crontab.conf
     RCLONE_SYNC_COMMAND: rclone version
    volumes:
     - ${CRONTAB_CONF_FILE}:/cron/crontab.conf
```

```bash
$ docker-compose up
Recreating rclone_test_rclone_1 ... done
Attaching to rclone_test_rclone_1
rclone_1  | SHELL=/bin/bash
rclone_1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
rclone_1  | 0 0 * * * curl -fsS --retry 3 ${RCLONE_HEALTHCHECK_URL}/start && /usr/bin/env bash -c "/rclone.sh run" && curl -fsS --retry 3 ${RCLONE_HEALTHCHECK_URL}set daemon 10
rclone_1  | set pidfile /var/run/monit.pid
rclone_1  | set statefile /var/run/monit.state
rclone_1  | set httpd port 2849 and
rclone_1  |     use address localhost
rclone_1  |     allow localhost
rclone_1  | set logfile syslog
rclone_1  | set eventqueue
rclone_1  |     basedir /var/run
rclone_1  |     slots 100
rclone_1  | include /etc/monit.d/*
rclone_1  |  New Monit id: 3706440245395bd6bb38adb47540bd2b
rclone_1  |  Stored in '/root/.monit.id'
rclone_1  | Starting Monit 5.25.1 daemon with http interface at [localhost]:2849
rclone_1  | /docker-entrypoint.sh: line 108: exec: : not found
rclone_test_rclone_1 exited with code 127
```

This leaves us users to think that the `command` field is meant as the command to be run in the cron.

You say `rclone.sh` is an example utility, but editing it ends up being kind of a hassle. Either 
 * we map it with a volume or 
 * we fork this repo to build it into the image.

If we map it, we remove the tracked code from the image, and everyone we want to share it with will need to clone and build it for themselves. If we do the latter, then we will need to clone and build it for ourselves instead of just being able to specify the image `image: openbridge/ob_bulkstash`
To avoid the mess, we end up with the `command: tail -f /dev/null` workaround :P 
It works, but I definitely agree that it is not expected behavior

**Comment by tspicer** [comment]
What is being highlighted is less an issue with the image, but the `rclone.sh` script. I will look at it more closely.

An argument can be made that this should not be included in the image at all. As I showed in the README, these types of controls might be left outside, not inside, the image. For example, running a script on the host (or other means). I'm not a Docker purist, so if `rclone.sh` is rising to be a "must" have then it will need some work.

**Comment by tspicer** [comment]
@Chovin the command is required by the image, not cron. If you want to use cron, then you need a command that will not exit the image once the process is ended. As a matter of fact, you have to supply some command for the image to do anything. This is not unique to this image, but almost all images at some level. 

This is why you can run `docker run openbridge/ob_bulkstash:latest rclone version` to get an output.
```
rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5
```
There is NO CMD set in the Dockerfile because that would effectively hard code a runtime command. For example, nginx might be `CMD ["/usr/sbin/nginx", "-g", "daemon off;"]` or with mysql it will be `CMD ["mysqld"]`. I can guarantee that if a valid CMD is not provided most images will exit or simply fail to start.  

Since we want a CMD to be user supplied, this is done via `docker-entrypoint.sh`
```
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD [""]
```
Unlike NGINX or MYSQL, there is no CMD set in this Dockerfile, the `docker-entrypoint.sh` expects a command to be present. You need to pass a command via docker-compose else you are not instructing the image to do anything. There is no rclone "server" mode. 

This is why you get `/docker-entrypoint.sh: line 108: exec: : not found`.  The image is saying, "hey, you never told me to do anything....".  This is no different than if I simply type `docker run openbridge/ob_bulkstash:latest`. The result? You guessed it;
```
/docker-entrypoint.sh: line 108: exec: : not found
```
I suggested using `command: bash` to persist the image, but there are a number of other acceptable methods. You get to choose, but you need to choose something that supports persistence.

So I'm not sure what you mean by leaving CMD out like other services means. Almost every docker image I know uses a CMD, either in the `Dockerfile` or via `docker-entrypoint.sh`. When it is included in a `Dockerfile`, normally it is static and runs as a persistent process. As a matter of fact, you are doing that very thing with `tail`. I think I need more help in understanding what you are attempting to describe.

On the use of `rclone.sh`, I'm not sure why someone would use it given how limited it is. Why not just put your rclone commands in your cron config?

**Comment by olivierdalang** [comment]
A few issues with a similar goal here !

The entrypoint script seems a bit bugged : 

- line 27 exits, as /cron/rclone.env doesn't exist (not even sure what it's supposed to be ?)
- it's very ambiguous whether you're supposed or not to provide a RCLONE_CRONFILE... it seems you need to provide a path, even if you want to cronfile to be created for you ?

Inspired by this repo, I quickly set up an extremely simplified version here, which does the job in my case : https://github.com/olivierdalang/docker-rclone-backup (only covers the crond use case)

**Comment by tspicer** [comment]
@olivierdalang ,

The docs  describes that to use `rclone.sh` requires specific ENV variables to be present. If you look at the `rclone.sh`, it is looking for this config;
```
# Create the environment file for crond
printenv | sed 's/^\([a-zA-Z0-9_]*\)=\(.*\)$/export \1="\2"/g' | grep -E "^export RCLONE" > /cron/rclone.env

source /cron/rclone.env
```
The script will then import these variables. Why is this done? The script can have difficulty picking up container ENV variables when it is run under CROND. CROND in many cases does not inherit the base OS ENV variables. Importing them makes sure they are present when running the script. 

So I think the file check resident in `docker-entrypoint.sh` stating `if [[ ! -f /cron/rclone.env ]]; then exit 1; fi` should be removed. I never really wanted to include or support the `rclone.sh` script, it was meant as an example utility so it has taken a life of its own. 

Also, why do you think it is ambiguous about the RCLONE_CRONFILE being required? The docs go into detail on this https://github.com/openbridge/ob_bulkstash#using-crond-inside-docker. Are you asking in relation to the `rclone.sh` script?

**Comment by tspicer** [comment]
@Chovin @GuillaumeLachaud @olivierdalang  I made some updates and posted. However, I want to point out that it appears in all cases you have not been running Docker in detached mode when you want to run `crond` in the background.

In the original docs I pointed out when using compose you should be setting `-d`,  so `docker-compose -d up` or `docker-compose -f ./compose/your.yml up -d --remove-orphans`. The same with normal `docker run -d` commands as well. 

I have updated the docs to make it clear the need to follow the standard Docker syntax for various runtime contexts, including a background process.
